### ISSUE TITLE
 public abstract interface PlayListRepository 

### ISSUE THREAD

**Issue by divy1219** [Charlieras262/BeatPlayer#1]
error: class PlayListRepository is public, should be declared in a file named PlayListRepository.java
public abstract interface PlayListRepository {

**Comment by rajpatel5** [comment]
It's because of the file name, but you are unable to change it, if you do it will just revert back. Then the error will appear again.

**Comment by divy1219** [comment]
yes fix to this problem

**Comment by rajpatel5** [comment]
I found a solution, Just change the filename in the repository folder to PlaylistsRepository and change the interface name inside that same file to PlaylistRepository. 

Note: Changing the filename will also cause you to change the class name and wherever that class is used in the app, so everywhere the class PlaylistRepository is used change it to PlaylistsRepository.

**Comment by Charlieras262** [comment]
**First of all, thanks for your interest in my project.**

Thanks for made me know the errors and now i found the solution for them, i already upload the solution on the repository and now you can download it.

Now with the problem about playing songs i put in the project description that it needs a playback service and i haven't enogh time to do it though.

**(I'm sorry for my english but i'm not a native english speaker)**
**I hope you have understood everything I typed.**
