### ISSUE TITLE
Notification cannot be removed

### ISSUE THREAD

**Issue by enwokoma** [Charlieras262/BeatPlayer#11]
As I pointed out in #10, this is yet another issue. When song is paused, I am unable to swipe off the notification
Also specific to Android 7

**Comment by Charlieras262** [comment]
I tested all changes i pushed in this commit to solve this issue, but i'm not completely sure, that's why i won't close the issue.

Please report if you experiment the error again.

**Comment by enwokoma** [comment]
As pointed out here in https://github.com/Charlieras262/BeatPlayer/issues/12#issuecomment-641296667, I would be closing this too and I haven't been able to reproduce the issue.
Would reopen if anything new comes up
