### ISSUE TITLE
Playback stuck

### ISSUE THREAD

**Issue by enwokoma** [Charlieras262/BeatPlayer#12]
In relation to #11, after pausing a song in an attempt to swipe out the notification (which didn't), I noticed that clicking on play to resume the song, it doesn't seem to work. The song is not playing.
Reported on Android 7

**Comment by Charlieras262** [comment]
Hi @enwokoma,

Tell me how do you test the app, with the release version or debug one.

Because i don't have the problem on my Crashlytics.

**Comment by enwokoma** [comment]
On debug. Android 7
Although it hasn't happened again since then.

**Comment by Charlieras262** [comment]
Hi @enwokoma,
could you please confirm if the playback stucks following the next steps?

1. Open the app.
2. Play some music.
3. Pause music in app.
4. Close the app.

The notification will desappear and then will appear and it's now when the playback stucks.

Thanks.

**Comment by enwokoma** [comment]
Yes. This is exactly the step to reproduce the issue. 
On Android 9+, there are no problems with the playback. But following your steps above on Android 7, the playback gets stuck, the notification refuses to go away either.

**Comment by Charlieras262** [comment]
I tested all changes i pushed in this commit to solve this issue, but i'm not completely sure, that's why i won't close the issue.

Please report if you experiment the error again.

**Comment by enwokoma** [comment]
Okay. Will test accordingly when I am bit free and revert back. The fix looks good and should be enough to solve the issue alongside #11

**Comment by enwokoma** [comment]
I would close this now as I haven't yet encountered the problem since then.
Would reopen if something comes up

**Comment by enwokoma** [comment]
I would have to reopen this because the pause/play button gets stuck at random (especially when playing from intent)
I think this is related to your commit at 5f21627. That commit might have broken a couple of things for the playback behavior

**Comment by enwokoma** [comment]
False alarm. The issue is from my end.
I didn't rebase properly to 5f21627 before building.I have traced the problem and rebased properly at 5f21627 and 8c144a4
Everything seems to work fine now.
