### ISSUE TITLE
Open music from another app (Intent)

### ISSUE THREAD

**Issue by enwokoma** [Charlieras262/BeatPlayer#16]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
It would be nice if the app can be able to play a song directly from another app e.g. from a file managers

![Screenshot_20200611-012244](https://user-images.githubusercontent.com/26168869/84331500-3f0aec00-ab82-11ea-9ec2-1ab83e11e456.png)

**Comment by Charlieras262** [comment]
Hi @enwokoma,
Yes, it would, actually i'm working on that.

**Comment by enwokoma** [comment]
Okay. Tested at this point: 5e3c09e. Everything looks fine but, the audioFocus doesn't seem to work when played from intent.

**Comment by Charlieras262** [comment]
I will check that.
Thanks.

**Comment by Charlieras262** [comment]
I found the solution, when you are able to test it, do it please.

**Comment by enwokoma** [comment]
This commit at de92ff1 has issues.
Check my comment at https://github.com/Charlieras262/BeatPlayer/commit/a8780006bbcc7eb151940b2c641cedeb6f206793#r39882192

**Comment by enwokoma** [comment]
One more thing I noticed is a bug in the playback and entire app behavior since the commits at 8b107c0 were made to fix this issue of opening music from intent.
I don't even know how to explain this problem or how to exactly reproduce it because it happens at random. Maybe, watching this screen record should show you what the problem feels like.
[Screen Record](https://drive.google.com/file/d/1O3iVLgH4A35QQp5KMJiqFMvsnfO19CXq/view)

**PS**: _I didn't want to create an entirely new issue for this since it is directly arising from here_
