### ISSUE TITLE
Song Doesn't play

### ISSUE THREAD

**Issue by PartapSBimrah** [Charlieras262/BeatPlayer#2]
When tried to play the song and click on that. but it doesn't play a song although click on the play button as well.

**Comment by telegramcore** [comment]
Same issue

**Comment by Charlieras262** [comment]
Hi guys, it occurred because does not have a playback service but i'm working on that though.

**Comment by PartapSBimrah** [comment]
ok

**Comment by muhammadfarooq012012** [comment]
Are you solve the issue?

**Comment by PartapSBimrah** [comment]
it still under progress

**Comment by muhammadfarooq012012** [comment]
Okay

**Comment by Charlieras262** [comment]
I already pushed a commit with the changes to solve this issue.

**Comment by muhammadfarooq012012** [comment]
Thanks Sir
