### ISSUE TITLE
[Bug] buggy behavior of the previous track button

### ISSUE THREAD

**Issue by machiav3lli** [Charlieras262/BeatPlayer#22]
**Describe the bug**
The previous track button doesn't provide a "good" functionality, especially when random is on (it plays the directly previous track in the list with no consideration that the real previous track has no connection with the order of the list).

**Expected behavior**
On first click if the track is already after the 5 seconds mark, restart the track from the start.
Else... Have two options:

1. go back to the last (really) played track (listed random playlist)

2. play a random track (fully randomness)

**Comment by Charlieras262** [comment]
Hi @machiav3lli, thanks for your comment, it isn't a bug because i wanted that it happens like that, because i don't handle the playlist when Shuffle Mode is on, but I will consider it for future enhancement.

**Comment by Charlieras262** [comment]
If you're experiencing this bug again feel free to reopen the issue.

Regards.
