### ISSUE TITLE
Need help to stop music on new activity

### ISSUE THREAD

**Issue by muhammadfarooq012012** [Charlieras262/BeatPlayer#23]
Hello,
First of all, I am very thankful to you for developing a great app with a beautiful and user-friendly interface and bug-free app. 

I have one question: 
I created another activity and on the new activity, I want to stop the music and dismiss the notification on button click. Can you please guide how I can do this. I spent many hours doing this but in vain. 

Looking forward to your response.
Thanks

**Comment by muhammadfarooq012012** [comment]
??

**Comment by Charlieras262** [comment]
Hi @muhammadfarooq012012 , thank you for your interest.

You can use dependency injections 

`val mainViewModel by inject<MainViewModel>`

Then something like this

`mainViewModel.transportControlls().play()`

Or even you can send a custom action

`mainViewModel.transportControlls().sendCustomAction("anction", bundleOf("extras","extras"))`

**Comment by enwokoma** [comment]
Hello @muhammadfarooq012012 have you tried what @Charlieras262 recommended? 
Dependency injection is your best shot to achieve what you want to do

**Comment by muhammadfarooq012012** [comment]
Hello,
Yes, I am tired and I am very thankful for the help.

**Comment by Charlieras262** [comment]
i'm glad to know you could did what you wanted.

If you need some help else, feel free to open an issue.
