### ISSUE TITLE
Not showing current playing song (Feature Removed) Why?

### ISSUE THREAD

**Issue by enwokoma** [Charlieras262/BeatPlayer#26]
So, I have been away for a while (on vacation). Got back recently and saw the amount of progress made so far.
I pulled at the most recent commit without vetting the previous commits individually.
At the most recent commit, everything works fine and no bugs detected (**so far**). But, I noticed a weirdly odd behavioral change in the app and i see it as an issue worth reporting.
When playing a song, I can't tell where exactly that current playing song is in the long list of songs on my device because the visual effect feature which marked the current playing song on the list with the visual effect showing at the left side of the song title has been removed in the recent updates.
This is a massive change that drastically affects the user experience (for me, in a wrong way). So, I think this should be addressed.

I am back for now. But, I might not dive back into writing code just yet until I feel ready. So, I do not know how exactly I would help you address a fix for this.

**Comment by Charlieras262** [comment]
Hi @enwokoma, I removed the feature because it affects the app performance, i think the way I was doing it, was not the best, i think i will add a queue list that i will appear when click in the queue indicator (1/200) in now playing view, but i not sure. If you have some suggestions it'll be great.

Regards.

**Comment by Charlieras262** [comment]
I'll add it, but i'll look for some way to do it better than it was before.

**Comment by enwokoma** [comment]
> Hi @enwokoma, I removed the feature because it affects the app performance, i think the way I was doing it, was not the best, i think i will add a queue list that i will appear when click in the queue indicator (1/200) in now playing view, but i not sure. If you have some suggestions it'll be great.
> 
> Regards.

Okay.
I will have a look at it soon to see if I can come up with something before you do

**Comment by enwokoma** [comment]
> I'll add it, but i'll look for some way to do it better than it was before.

Okay then. No problem
I've been really occupied these past couple of days anyways.

**Comment by Charlieras262** [comment]
The commit f05508e should solve this issue
