### ISSUE TITLE
App crashes on playing song.

### ISSUE THREAD

**Issue by General-OB1** [Charlieras262/BeatPlayer#3]
Music app opens & everything is working fine but as soon as you tap on any song to play it crashes.

 - Device: Asus Zenfone Max Pro M1
 - OS: MSM Extended v6.0

https://del.dog/unycavimum
I have uploaded crash log on above link.

**Comment by imukesh1337** [comment]
What are your Gradle and SDK Versions?

**Comment by enessgokalp** [comment]
Android 8.0
EMUI 8.0


26 Mar 2020 Per 14:07 tarihinde Mukesh Bhardwaj <notifications@github.com>
şunu yazdı:

**Comment by manojkumarsmks** [comment]
Can I work on this issue ?

**Comment by Charlieras262** [comment]
@manojkumarsmks 

> Can I work on this issue ?

Yes, you can.

**Comment by Charlieras262** [comment]
Hi,
The problem was caused by the audio2Raw method in the GeneralUtils.kt file, because According to the [Android documentation](https://developer.android.com/training/data-storage#scoped-storage): 

> Apps targeting Android 10 (API level 29) and higher are given scoped access into an external storage device, or scoped storage, by default. Such apps can see only their app-specific directory.

I found the solution for this issue and i already pushed the commit that will fix it.
