### ISSUE TITLE
Sometimes music was skipped 1s when next or previous music

### ISSUE THREAD

**Issue by AyraHikari** [Charlieras262/BeatPlayer#30]
**Describe the bug**
When next or previous button clicked (by notification or in app), sometimes it skipped one second from music.

**To Reproduce**
1. Play a music
2. Tap next or previous button from app or notification
3. It sometimes skipped 1s and start from 00:01

**Screenshots**
Here is screen record, hear at 'Can't wait until night', at first it play from 00:01, then the second it works and play from 00:00
> [Video Preview](https://telegra.ph/file/cfdd9fa1ca34a95000489.mp4)

**Smartphone:**
 - Device: Xiaomi Redmi Note 5 Pro
 - OS: MIUI 12 (Android 10)
 - Browser: stock browser
 - Version: 1.0.0

**Comment by Charlieras262** [comment]
The pull request #31 should fix this issue but if you experience the error again feel free to reopen this issue.
