### ISSUE TITLE
Potential spelling and grammar fixes in README

### ISSUE THREAD

**Issue by bg-write** [Charlieras262/BeatPlayer#35]
Noticed a few spelling errors in the README, such as "Designe" rather than "Material Design," unless that was intentional? Would love to create a PR to tweak the overall README for light editing for spelling, grammar, and clarity.

**Comment by Charlieras262** [comment]
Hello @bg-write, thank you for your interest in this project, I would be completely agree and grateful for your support in improving the clarity and spelling of the README file.

**Comment by bg-write** [comment]
Excellent! I'll get started on that PR.
