### ISSUE TITLE
Sugestion: Avoid using real threads.

### ISSUE THREAD

**Issue by jeancsanchez** [Charlieras262/BeatPlayer#4]
Hello! Great app, congratulations!

I think using real threads in the app can cause many problems with performance and state management. I really advise you to use another way for threading in your application like [Coroutines](https://kotlinlang.org/docs/reference/coroutines-overview.html), since you are using Kotlin as language.
https://github.com/Charlieras262/BeatPlayer/blob/bc3d94fce14b7205ea9d90aa2d6cbab7b43866af/app/src/main/java/com/crrl/beatplayer/ui/viewmodels/FavoriteViewModel.kt#L46

**Comment by Charlieras262** [comment]
Hi, thanks for your advice.

I already changed the real threads, now i'm using Coroutines instead and i can see that the performance is much better than it was before.

I already pushed a commit with the changes for this suggestion.

Have a great day.
