### ISSUE TITLE
Status bar display bug

### ISSUE THREAD

**Issue by enwokoma** [Charlieras262/BeatPlayer#5]
**Describe the bug**
The settings page goes under the status bar

**To Reproduce**

**Expected behavior**
The settings page needs to be placed directly under the status like it is in the mainactivity

**Screenshots**
![Screenshot_20200521-161033](https://user-images.githubusercontent.com/26168869/82574041-763b3e00-9b7e-11ea-8720-33581583b295.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Charlieras262** [comment]
Hi @enwokoma, thanks for your interest.

I already pushed a commit to solve the issue.

Have a good day.
