### ISSUE TITLE
Lyrics page not complete? 

### ISSUE THREAD

**Issue by enwokoma** [Charlieras262/BeatPlayer#7]
**Describe the bug**
The lyrics section does not have a button to navigate backwards to the previous page (now playing). But when I click around that region, it works (it goes goes back to the previous page). 

![Screenshot_20200522-080443](https://user-images.githubusercontent.com/26168869/82646024-bd234500-9c0b-11ea-9ee1-a850cb635bd5.png)

**Comment by Charlieras262** [comment]
Thank you very much @enwokoma  for helping to improve the project.
